openapi: 3.0.0
info:
  title: Todo API
  description: RESTful API für die Verwaltung von Todo-Listen
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v1
    description: Produktionsserver

security:
  - apiKey: []

paths:
  /users:
    get:
      summary: Alle Benutzer abrufen
      operationId: getUsers
      tags:
        - Users
      responses:
        '200':
          description: Liste der Benutzer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Interner Server-Fehler

    post:
      summary: Neuen Benutzer erstellen
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Benutzer erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ungültige Eingabe

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: Benutzer-ID

    get:
      summary: Benutzer nach ID abrufen
      operationId: getUserById
      tags:
        - Users
      responses:
        '200':
          description: Benutzer gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    put:
      summary: Benutzer aktualisieren
      operationId: updateUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Benutzer aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    delete:
      summary: Benutzer löschen
      operationId: deleteUser
      tags:
        - Users
      responses:
        '204':
          description: Benutzer gelöscht
        '404':
          description: Benutzer nicht gefunden

  /users/{userId}/todos:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Alle Todos eines Benutzers abrufen
      operationId: getUserTodos
      tags:
        - Todos
      parameters:
        - name: status
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - OPEN
              - IN_PROGRESS
              - COMPLETED
          description: Filter nach Status
      responses:
        '200':
          description: Liste der Todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      summary: Neues Todo erstellen
      operationId: createTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
          application/xml:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Todo erstellt
          headers:
            X-Request-Id:
              schema:
                type: string
              description: Eindeutige Request-ID
            X-Response-Time:
              schema:
                type: integer
              description: Antwortzeit in Millisekunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          links:
            GetTodoById:
              $ref: '#/components/links/GetTodoById'
      callbacks:
        todoStatusChanged:
          $ref: '#/components/callbacks/todoStatusChanged'

  /users/{userId}/todos/{todoId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Todo nach ID abrufen
      operationId: getTodoById
      tags:
        - Todos
      parameters:
        - name: includeDetails
          in: query
          required: false
          schema:
            type: boolean
          description: Detaillierte Informationen einschließen
        - name: format
          in: query
          required: false
          schema:
            type: string
          description: Ausgabeformat
      responses:
        '200':
          description: Todo gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo nicht gefunden
        '410':
          description: Todo wurde gelöscht

    put:
      summary: Todo aktualisieren
      operationId: updateTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Todo aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

    delete:
      summary: Todo löschen
      operationId: deleteTodo
      tags:
        - Todos
      responses:
        '204':
          description: Todo gelöscht
        '404':
          description: Todo nicht gefunden

  /categories:
    get:
      summary: Alle Kategorien abrufen
      operationId: getCategories
      tags:
        - Categories
      responses:
        '200':
          description: Liste der Kategorien
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Neue Kategorie erstellen
      operationId: createCategory
      tags:
        - Categories
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
          application/xml:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Kategorie erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
        - email
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john@example.com
        createdAt:
          type: string
          format: date-time

    UserInput:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email

    Todo:
      type: object
      required:
        - id
        - title
        - status
        - userId
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Einkaufen gehen
        description:
          type: string
          example: Milch, Brot und Eier kaufen
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            - URGENT
        userId:
          type: integer
          format: int64
        categoryId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    TodoInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
          default: OPEN
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            - URGENT
          default: MEDIUM
        categoryId:
          type: integer
          format: int64
          readOnly: false
          writeOnly: false

    Category:
      type: object
      required:
        - id
        - name
        - color
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Work
          minLength: 1
          maxLength: 100
        description:
          type: string
          example: Work-related tasks
        color:
          type: string
          example: "#FF5733"
        icon:
          type: string
          example: briefcase
        priority:
          type: integer
          minimum: 1
          maximum: 100
        tags:
          type: array
          items:
            type: string
          minItems: 0
          maxItems: 20
        metadata:
          type: object
          additionalProperties:
            type: string

    CategoryInput:
      type: object
      required:
        - name
        - color
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        description:
          type: string
          maxLength: 200
        color:
          type: string
          pattern: "^#[0-9A-Fa-f]{6}$"
        icon:
          type: string

    Notification:
      type: object
      required:
        - notificationType
      properties:
        notificationType:
          type: string
      discriminator:
        propertyName: notificationType
        mapping:
          email: '#/components/schemas/EmailNotification'
          sms: '#/components/schemas/SmsNotification'
      oneOf:
        - $ref: '#/components/schemas/EmailNotification'
        - $ref: '#/components/schemas/SmsNotification'

    EmailNotification:
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          required:
            - emailAddress
          properties:
            emailAddress:
              type: string
              format: email
            subject:
              type: string

    SmsNotification:
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          required:
            - phoneNumber
          properties:
            phoneNumber:
              type: string
              pattern: "^\\+[1-9]\\d{1,14}$"
            message:
              type: string
              maxLength: 160

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:todos: Todos lesen
            write:todos: Todos schreiben
            delete:todos: Todos löschen
            admin: Administratorrechte

  responses:
    UnauthorizedError:
      description: Zugriff verweigert - Authentifizierung erforderlich
      headers:
        X-Rate-Limit:
          schema:
            type: integer
          description: Anzahl der verbleibenden Anfragen
        X-Rate-Limit-Reset:
          schema:
            type: string
            format: date-time
          description: Zeitpunkt des Rate-Limit-Resets

  callbacks:
    todoStatusChanged:
      '{$request.body#/callbackUrl}':
        post:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    todoId:
                      type: integer
                    newStatus:
                      type: string
          responses:
            '200':
              description: Callback erfolgreich

  links:
    GetTodoById:
      operationId: getTodoById
      parameters:
        todoId: '$response.body#/id'
        userId: '$response.body#/userId'
