openapi: 3.0.0
info:
  title: Todo API
  description: RESTful API für die Verwaltung von Todo-Listen (Version 2 mit Breaking Changes)
  version: 2.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v2
    description: Produktionsserver V2

paths:
  /users:
    get:
      summary: Alle Benutzer abrufen
      operationId: getUsers
      tags:
        - Users
      parameters:
        # BREAKING CHANGE: Neuer required Parameter
        - name: includeInactive
          in: query
          required: true
          schema:
            type: boolean
          description: Inaktive Benutzer einschließen
      responses:
        '200':
          description: Liste der Benutzer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Interner Server-Fehler

    post:
      summary: Neuen Benutzer erstellen
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        # BREAKING CHANGE: Response-Code geändert von 200 zu 201
        '201':
          description: Benutzer erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ungültige Eingabe

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: Benutzer-ID

    get:
      summary: Benutzer nach ID abrufen
      operationId: getUserById
      tags:
        - Users
      responses:
        '200':
          description: Benutzer gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    put:
      summary: Benutzer aktualisieren
      operationId: updateUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Benutzer aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    # BREAKING CHANGE: DELETE-Methode wurde entfernt!
    # delete endpoint wurde entfernt - Benutzer können nicht mehr gelöscht werden

  /users/{userId}/todos:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Alle Todos eines Benutzers abrufen
      operationId: getUserTodos
      tags:
        - Todos
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - OPEN
              - IN_PROGRESS
              - COMPLETED
              - CANCELLED  # Neuer Enum-Wert (nicht breaking)
          description: Filter nach Status
      responses:
        '200':
          description: Liste der Todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      summary: Neues Todo erstellen
      operationId: createTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '201':
          description: Todo erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /users/{userId}/todos/{todoId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Todo nach ID abrufen
      operationId: getTodoById
      tags:
        - Todos
      parameters:
        # BREAKING: includeDetails Parameter entfernt
        # BREAKING: format Parameter hat jetzt required: true (war optional)
        - name: format
          in: query
          required: true
          schema:
            type: integer  # BREAKING: Typ von string zu integer geändert
          description: Ausgabeformat (1=JSON, 2=XML)
        # NON-BREAKING: Neuer optionaler Parameter
        - name: includeHistory
          in: query
          required: false
          schema:
            type: boolean
          description: Historie einschließen
      responses:
        '200':
          description: Todo gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoDetailed'  # BREAKING: Schema geändert
        '404':
          description: Todo nicht gefunden
        # BREAKING: Response 410 wurde entfernt

    put:
      summary: Todo aktualisieren
      operationId: updateTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdateInput'  # BREAKING: Request-Schema geändert
      responses:
        '200':
          description: Todo aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

    delete:
      summary: Todo löschen
      operationId: deleteTodo
      tags:
        - Todos
      responses:
        '204':
          description: Todo gelöscht
        '404':
          description: Todo nicht gefunden

    # NON-BREAKING: Neue PATCH-Methode hinzugefügt
    patch:
      summary: Todo teilweise aktualisieren
      operationId: patchTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Todo teilweise aktualisiert

  # NON-BREAKING: Neuer Endpoint hinzugefügt
  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: System is healthy

  # BREAKING: /categories Endpoint wurde komplett entfernt!

components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
        - email
        - accountType  # BREAKING CHANGE: Neues required Feld
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john@example.com
        accountType:
          type: string
          enum:
            - FREE
            - PREMIUM
          description: Account-Typ (neu in V2)
        createdAt:
          type: string
          format: date-time
        # BREAKING CHANGE: 'isActive' Feld hinzugefügt (nicht required, daher weniger kritisch)
        isActive:
          type: boolean
          default: true

    UserInput:
      type: object
      required:
        - username
        - email
        - accountType  # BREAKING CHANGE: Neues required Feld im Input
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        accountType:
          type: string
          enum:
            - FREE
            - PREMIUM

    Todo:
      type: object
      required:
        - id
        - title
        - status
        - userId
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Einkaufen gehen
        description:
          type: string
          example: Milch, Brot und Eier kaufen
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED  # Neuer Enum-Wert
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            # BREAKING CHANGE: URGENT wurde entfernt
        userId:
          type: integer
          format: int64
        # BREAKING: categoryId wurde entfernt
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: integer  # BREAKING: Typ von string zu integer geändert (Unix timestamp)
        # Neues Feld (nicht breaking, da nicht required)
        dueDate:
          type: string
          format: date

    TodoInput:
      type: object
      required:
        - title
        - priority  # BREAKING CHANGE: priority wurde zu required
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
        # categoryId wurde entfernt
        dueDate:
          type: string
          format: date

    TodoDetailed:
      type: object
      required:
        - id
        - title
        - status
        - userId
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: integer
        dueDate:
          type: string
          format: date
        history:
          type: array
          items:
            type: object

    TodoUpdateInput:
      type: object
      required:
        - title
        - priority
      properties:
        title:
          type: string
        priority:
          type: string
        status:
          type: string
        description:
          type: string

