openapi: 3.0.0
info:
  title: Todo API
  description: RESTful API für die Verwaltung von Todo-Listen (Version 2 mit Breaking Changes)
  version: 2.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v2
    description: Produktionsserver V2

security:
  - oauth2: [read:todos, write:todos]  # BREAKING: Security requirement added to global level

paths:
  /users:
    get:
      summary: Alle Benutzer abrufen
      operationId: getUsers
      tags:
        - Users
      parameters:
        # BREAKING CHANGE: Neuer required Parameter
        - name: includeInactive
          in: query
          required: true
          schema:
            type: boolean
          description: Inaktive Benutzer einschließen
      responses:
        '200':
          description: Liste der Benutzer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Interner Server-Fehler

    post:
      summary: Neuen Benutzer erstellen
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        # BREAKING CHANGE: Response-Code geändert von 200 zu 201
        '201':
          description: Benutzer erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ungültige Eingabe

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
        description: Benutzer-ID

    get:
      summary: Benutzer nach ID abrufen
      operationId: getUserById
      tags:
        - Users
      responses:
        '200':
          description: Benutzer gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    put:
      summary: Benutzer aktualisieren
      operationId: updateUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Benutzer aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Benutzer nicht gefunden

    # BREAKING CHANGE: DELETE-Methode wurde entfernt!
    # delete endpoint wurde entfernt - Benutzer können nicht mehr gelöscht werden

  /users/{userId}/todos:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Alle Todos eines Benutzers abrufen
      operationId: getUserTodos
      tags:
        - Todos
      parameters:
        - name: status
          in: query
          required: false
          style: spaceDelimited  # BREAKING: Parameter style changed from 'form' to 'spaceDelimited'
          explode: false  # BREAKING: Parameter explode changed from true to false
          schema:
            type: string
            enum:
              - OPEN
              - IN_PROGRESS
              - COMPLETED
              - CANCELLED  # Neuer Enum-Wert (nicht breaking)
          description: Filter nach Status
      responses:
        '200':
          description: Liste der Todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      summary: Neues Todo erstellen
      operationId: createTodo
      deprecated: true  # WARNING: Operation marked as deprecated
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
          # BREAKING: application/xml content type removed
      responses:
        '201':
          description: Todo erstellt
          headers:
            X-Request-Id:
              schema:
                type: string
              description: Eindeutige Request-ID
            # BREAKING: X-Response-Time header removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
            # NON-BREAKING: New content type added
            application/xml:
              schema:
                $ref: '#/components/schemas/Todo'
          links:
            GetUserTodos:
              $ref: '#/components/links/GetUserTodos'
      callbacks:
        todoCreated:
          $ref: '#/components/callbacks/todoCreated'

  /users/{userId}/todos/{todoId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      summary: Todo nach ID abrufen
      operationId: getTodoById
      tags:
        - Todos
      parameters:
        # BREAKING: includeDetails Parameter entfernt
        # BREAKING: format Parameter hat jetzt required: true (war optional)
        - name: format
          in: query
          required: true
          schema:
            type: integer  # BREAKING: Typ von string zu integer geändert
          description: Ausgabeformat (1=JSON, 2=XML)
        # NON-BREAKING: Neuer optionaler Parameter
        - name: includeHistory
          in: query
          required: false
          schema:
            type: boolean
          description: Historie einschließen
      responses:
        '200':
          description: Todo gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoDetailed'  # BREAKING: Schema geändert
        '404':
          description: Todo nicht gefunden
        # BREAKING: Response 410 wurde entfernt

    put:
      summary: Todo aktualisieren
      operationId: updateTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdateInput'  # BREAKING: Request-Schema geändert
      responses:
        '200':
          description: Todo aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

    delete:
      summary: Todo löschen
      operationId: deleteTodo
      tags:
        - Todos
      responses:
        '204':
          description: Todo gelöscht
        '404':
          description: Todo nicht gefunden

    # NON-BREAKING: Neue PATCH-Methode hinzugefügt
    patch:
      summary: Todo teilweise aktualisieren
      operationId: patchTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Todo teilweise aktualisiert

  # NON-BREAKING: Neuer Endpoint hinzugefügt
  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: System is healthy

  /categories:
    get:
      summary: Alle Kategorien abrufen
      operationId: getCategories
      deprecated: true  # WARNING: Schema deprecated
      tags:
        - Categories
      responses:
        '200':
          description: Liste der Kategorien
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Neue Kategorie erstellen
      operationId: createCategory
      tags:
        - Categories
      requestBody:
        required: true  # BREAKING: Request body became required (was false in v1)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
          # BREAKING: application/xml content type removed
      responses:
        '201':
          description: Kategorie erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

  # BREAKING: /categories Endpoint wurde komplett entfernt!

components:
  schemas:
    User:
      type: object
      required:
        - id
        - username
        - email
        - accountType  # BREAKING CHANGE: Neues required Feld
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john@example.com
        accountType:
          type: string
          enum:
            - FREE
            - PREMIUM
          description: Account-Typ (neu in V2)
        createdAt:
          type: string
          format: date-time
        # BREAKING CHANGE: 'isActive' Feld hinzugefügt (nicht required, daher weniger kritisch)
        isActive:
          type: boolean
          default: true

    UserInput:
      type: object
      required:
        - username
        - email
        - accountType  # BREAKING CHANGE: Neues required Feld im Input
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        accountType:
          type: string
          enum:
            - FREE
            - PREMIUM

    Todo:
      type: object
      required:
        - id
        - title
        - status
        - userId
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Einkaufen gehen
        description:
          type: string
          example: Milch, Brot und Eier kaufen
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED  # Neuer Enum-Wert
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            # BREAKING CHANGE: URGENT wurde entfernt
        userId:
          type: integer
          format: int64
        # BREAKING: categoryId wurde entfernt
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: integer  # BREAKING: Typ von string zu integer geändert (Unix timestamp)
        # Neues Feld (nicht breaking, da nicht required)
        dueDate:
          type: string
          format: date

    TodoInput:
      type: object
      required:
        - title
        - priority  # BREAKING CHANGE: priority wurde zu required
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED
          default: IN_PROGRESS  # BREAKING: Default value changed from OPEN to IN_PROGRESS
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
          # BREAKING: Default value removed (was MEDIUM in v1)
          deprecated: true  # WARNING: Parameter deprecated
        # categoryId wurde entfernt
        dueDate:
          type: string
          format: date
          readOnly: true  # BREAKING: readOnly changed from false to true
          writeOnly: false

    TodoDetailed:
      type: object
      required:
        - id
        - title
        - status
        - userId
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - IN_PROGRESS
            - COMPLETED
            - CANCELLED
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
        userId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: integer
        dueDate:
          type: string
          format: date
        history:
          type: array
          items:
            type: object

    TodoUpdateInput:
      type: object
      required:
        - title
        - priority
      properties:
        title:
          type: string
        priority:
          type: string
        status:
          type: string
        description:
          type: string

    Category:
      type: object
      required:
        - id
        - name
        - color
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Work
          minLength: 3  # BREAKING: minLength increased from 1 to 3
          maxLength: 80  # BREAKING: maxLength decreased from 100 to 80
        description:
          type: string
          example: Work-related tasks
        color:
          type: string
          example: "#FF5733"
        icon:
          type: string
          example: briefcase
        priority:
          type: integer
          minimum: 10  # BREAKING: minimum increased from 1 to 10
          maximum: 50  # BREAKING: maximum decreased from 100 to 50
        tags:
          type: array
          items:
            type: string
          minItems: 1  # BREAKING: minItems increased from 0 to 1
          maxItems: 10  # BREAKING: maxItems decreased from 20 to 10
          uniqueItems: true  # BREAKING: uniqueItems constraint added
        metadata:
          type: object
          additionalProperties: false  # BREAKING: additionalProperties forbidden (was type: string)

    CategoryInput:
      type: object
      required:
        - name
        - color
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        description:
          type: string
          maxLength: 200
        color:
          type: string
          pattern: "^#[0-9A-Fa-f]{6}$"
        icon:
          type: string

    Notification:
      type: object
      required:
        - notificationType
      properties:
        notificationType:
          type: string
      discriminator:
        propertyName: type  # BREAKING: discriminator property name changed from 'notificationType' to 'type'
        mapping:
          email: '#/components/schemas/EmailNotification'
          # BREAKING: sms mapping removed from oneOf
      oneOf:
        - $ref: '#/components/schemas/EmailNotification'
        # BREAKING: SmsNotification option removed from oneOf

    EmailNotification:
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          required:
            - emailAddress
          properties:
            emailAddress:
              type: string
              format: email
            subject:
              type: string

    SmsNotification:
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          required:
            - phoneNumber
          properties:
            phoneNumber:
              type: string
              pattern: "^\\+[1-9]\\d{1,14}$"
            message:
              type: string
              maxLength: 160

  securitySchemes:
    apiKey:
      type: http  # BREAKING: Security scheme type changed from 'apiKey' to 'http'
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        clientCredentials:  # BREAKING: OAuth flow changed from 'authorizationCode' to 'clientCredentials'
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:todos: Todos lesen
            write:todos: Todos schreiben
            # BREAKING: 'delete:todos' scope removed
            # BREAKING: 'admin' scope removed

  responses:
    UnauthorizedError:
      description: Zugriff verweigert - Authentifizierung erforderlich
      headers:
        X-Rate-Limit:
          schema:
            type: integer
          description: Anzahl der verbleibenden Anfragen
          required: true  # BREAKING: Response header became required
        # BREAKING: X-Rate-Limit-Reset header removed

  callbacks:
    todoStatusChanged:
      '{$request.body#/webhookUrl}':  # BREAKING: Callback URL changed from 'callbackUrl' to 'webhookUrl'
        post:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    todoId:
                      type: integer
                    newStatus:
                      type: string
          responses:
            '200':
              description: Callback erfolgreich
    # New callback added (non-breaking)
    todoCreated:
      '{$request.body#/webhookUrl}':
        post:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
          responses:
            '200':
              description: Todo created callback

  links:
    # BREAKING: GetTodoById link removed
    GetUserTodos:
      operationId: getUserTodos
      parameters:
        userId: '$response.body#/userId'
